# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 2) do

  create_table "tweets", :force => true do |t|
    t.column "text",       :string
    t.column "user_id",    :integer
    t.column "created_at", :datetime
  end

  add_index "tweets", ["user_id"], :name => "index_tweets_on_user_id"

  create_table "users", :force => true do |t|
    t.column "screen_name", :string, :limit => 32
    t.column "name",        :string, :limit => 100
    t.column "bio",         :string
    t.column "location",    :string, :limit => 100
    t.column "url",         :string
  end

  add_index "users", ["name"], :name => "index_users_on_name"
  add_index "users", ["screen_name"], :name => "index_users_on_screen_name", :unique => true

end
