#!/usr/bin/env ruby

require 'rubygems/specification'
data = File.read(File.join(File.dirname(__FILE__), '..', 'twitter4r.gemspec'))
spec = nil
Thread.new { spec = eval("$SAFE = 3\n#{data}") }.join
puts spec.inspect